name: Run CI checks # The name will show up on the GitHub Actions dashboard

on: [pull_request] # This workflow will run only on Pull Requests

env:
  NX_BRANCH: ${{ github.event.pull_request.head.ref }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  # test-store: # give our job an ID
  #   runs-on: ubuntu-latest # the image our job will run on
  #   name: Test Store # the name that will appear on the Actions UI
  #   steps: # what steps it will perform
  #     - uses: actions/checkout@v1 # checkout whatever branch the PR is using
  #     - uses: bahmutov/npm-install@v1 # trigger an `npm install`
  #     - run: npm run nx test store # test the "store" project
  # test-api:
  #   runs-on: ubuntu-latest
  #   name: Test API
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: bahmutov/npm-install@v1
  #     - run: npm run nx test api
  # indentation is important
  test:
    runs-on: ubuntu-latest
    name: Testing affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: npm run nx affected -- --target=test --base=origin/master --parallel
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: npm run nx affected -- --target=lint --base=origin/master --parallel
  e2e:
    runs-on: ubuntu-latest
    name: E2E
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: npm run nx affected -- --target=e2e --base=origin/master --parallel
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: npm run nx affected -- --target=build --base=origin/master --parallel
